vim.opt.rtp:prepend(vim.fn.stdpath('config') .. '/lua')

require('futheline').setup({
	theme = 'github_dark',
	preset = "vscode",
	-- components = {
	-- 	left = {
	-- 		{
	-- 			'mode',
	-- 			hl = {
	-- 				bg = "mode",
	-- 				fg = "#ffffff"
	-- 			},
	-- 			border_right = {
	-- 				style = "round",
	-- 				hl = {
	-- 					fg = "mode"
	-- 				}
	-- 			}
	-- 		},
	-- 		{
	-- 			'file',
	-- 			empty_name = "[Sin nombre]",
	-- 			hl = {
	-- 				fg = "#ffffff",
	-- 				bg = "#8888ff"
	-- 			},
	-- 			border_left = {
	-- 				style = 'round',
	-- 				hl = {
	-- 					fg = "#aaaaff",
	-- 				}
	-- 			},
	-- 			border_right = {
	-- 				style = 'round',
	-- 				hl = {
	-- 					fg = "#6666ff",
	-- 				}
	-- 			},
	-- 			icon_hl = {
	-- 				fg = '#000000',
	-- 				bg = '#aaaaff'
	-- 			}
	-- 		},
	-- 	},
	-- 	center = {
	-- 		{ 'git', {
	-- 			border = "none",
	-- 			border_left = {
	-- 				style = "none"
	-- 			},
	-- 			border_right = {
	-- 				style = "none"
	-- 			}
	-- 		} },
	-- 	},
	-- 	right = {
	-- 		{ 'diagnostics', {
	-- 			border = "none",
	-- 			border_left = {
	-- 				style = "none"
	-- 			},
	-- 			border_right = {
	-- 				style = "none"
	-- 			}
	-- 		} },
	-- 		{
	-- 			'lsp',
	-- 			border_left = {
	-- 				style = "round",
	-- 				hl = {
	-- 					fg = "#aaaaff",
	-- 				}
	-- 			},
	-- 			border_right = {
	-- 				style = "round",
	-- 				hl = {
	-- 					fg = "#6666ff"
	-- 				}
	-- 			},
	-- 			icon_hl = {
	-- 				fg = '#000000',
	-- 				bg = '#aaaaff'
	-- 			},
	-- 			hl = {
	-- 				bg = "#6666ff",
	-- 				fg = "#ffffff"
	-- 			},
	-- 		},
	-- 		{
	-- 			'position',
	-- 			hl = {
	-- 				bg = "#6666ff",
	-- 				fg = "#ffffff"
	-- 			},
	-- 			border_left = {
	-- 				style = "round",
	-- 				fg = "#aaaaff"
	-- 			},
	-- 			border_right = {
	-- 				style = "round",
	-- 				fg = "#6666ff",
	-- 			},
	-- 			icon_hl = {
	-- 				fg = '#000000',
	-- 				bg = '#aaaaff'
	-- 			}
	-- 		},
	-- 	}
	-- },
})
